main/urls.py
from django.urls import path,include
from . import views

app_name = "main"
urlpatterns = [
    path('',views.home,name="index"),
    path('login/',views.login_template,name="login"),
    path('achievements/',views.achievements_template,name="achivements"),
    path('contributers/',views.contributers_template,name="contributers"),
    path('aboutus/',views.aboutus_template,name="aboutus"),
    path('register/<slug:slug>',views.register_template,name="register"),
    path('register2/<slug:user_id>',views.register2_template,name="register2"),
    path('logout',views.logout_url,name="logout"),
    path('apply-to-donate',views.apply_donate,name="apply_donate") 
]

ngo/urls.py
from django.urls import path,include
from . import views

app_name = "ngo"
urlpatterns = [
    path('ngo/dashboard',views.dashboard,name="dashboard"),
]

saveplate/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('',include('user.urls')),
    path('',include('ngo.urls')),
    path('',include('org.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class UserDetials(models.Model):
    
    USER_TYPE =  (
        ("0","ADMIN"),
        ("1","FOOD RETAILER"),
        ("2","ORGANIZATION"),
        ("3","NGO"),
        ("4","USER")
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.TextField(max_length=400, blank=True,null=True)
    state = models.CharField(max_length=255,blank=True,null=True)
    city = models.CharField(max_length=255,blank=True,null=True)
    pincode = models.IntegerField(blank=True,null=True)
    phone = models.BigIntegerField(blank=True,null=True)
    type = models.CharField(max_length=20,choices=USER_TYPE,blank=True, null=True)
    
    class Meta:
        db_table = "USER_DETAILS"
        
class Donations(models.Model):
    
    food_name = models.CharField(max_length=255,null=True,blank=True)
    plate_size = models.IntegerField(default=0,null=True,blank=True)
    reason = models.TextField(null=True,blank=True)
    from_user = models.ForeignKey(User, related_name="FromUser", on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name="ToUser", on_delete=models.CASCADE)
    applied_at = models.DateTimeField(blank=True, null=True)
    received_status = models.BooleanField(default=False)
    received_at = models.DateTimeField(blank=True, null=True)
    donated_status = models.BooleanField(default=False)
    donated_at = models.DateTimeField(blank=True, null=True)
    donated_at_location = models.TextField(blank=True,null=True)
    image = models.ImageField(upload_to='uploads/donations/images/',blank=True,null=True)
    
    class Meta:
        db_table = "DONATIONS"

main/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password,check_password
from .models import UserDetials,Donations
from django.contrib import messages 
from datetime import datetime
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request,template_name="main/index.html"):
    return render(request,template_name)


def achievements_template(request,template_name="main/achievements.html"):
    return render(request,template_name)

def contributers_template(request,template_name="main/contributers.html"):
    return render(request,template_name)

def aboutus_template(request,template_name="main/aboutus.html"):
    return render(request,template_name)

@csrf_exempt
def login_template(request,template_name="main/login.html"):
    if request.method == "POST":
        try:
            postdata = request.POST
            username = postdata['username']
            password = postdata['password']
            try:
                user = authenticate(username=username, password=password)
            except:
                user = None
            if user is not None:
                login(request,user)
                user_details_obj = UserDetials.objects.get(user__id=user.id)
                messages.success(request, "Logged In" )
                if user_details_obj.type == '2':
                    return redirect('org:dashboard')
                elif user_details_obj.type == '3':
                    return redirect('ngo:dashboard')
                elif user_details_obj.type == '4':
                    return redirect('user:dashboard')
            else:
                messages.error(request, "User not found")
        except Exception as e:
            messages.error(request, "Some Error Occured")

    return render(request,template_name)


@csrf_exempt
def register_template(request,slug,template_name="main/register.html"):
    type= slug
    if request.method == "POST":
        postdata = request.POST
        # try:
        username = postdata['username']
        password = make_password(postdata['password'])
        first_name = postdata['name']
        email = postdata['email']
        phone = int(postdata['phone'])
        type = postdata['type']
        try:
            user = User.objects.get(Q(username=username) | Q(email=email))
        except:
            user = None
        if user ==  None:
            user = User.objects.create(username=username,password=password,email=email,first_name=first_name)
            UserDetials.objects.create(user=user,phone=phone,type=type)
            login(request,user)
            messages.success(request, "Registered Successfully" )
            return redirect('main:register2',user_id=user.id)
        else:
            messages.error(request, "Username or Email already Exists.")
            messages.error(request, "Some Error Occured")
    return render(request,template_name,{'type': type})


@csrf_exempt
def register2_template(request,user_id,template_name="main/register2.html"):
    user_id = user_id
    if request.method == "POST":
        postdata = request.POST
        try:
            id = postdata['id']
            address = postdata['address']
            state = postdata['state']
            city = postdata['city']
            pincode = postdata['pincode']
            try:
                user_details_obj = UserDetials.objects.get(user__id=id)
            except:
                user_details_obj = None
            if user_details_obj:
                user_details_obj.address = address
                user_details_obj.state = state
                user_details_obj.city = city
                user_details_obj.pincode = pincode
                user_details_obj.save()
                messages.success(request, "Address details updated Successfully.")
                if user_details_obj.type == '2':
                    return redirect('org:dashboard')
                elif user_details_obj.type == '3':
                    return redirect('ngo:dashboard')
                elif user_details_obj.type == '4':
                    return redirect('user:dashboard')
            else:
                messages.error(request, "User not found.")
        except Exception as e:
            print(e)
            messages.error(request, "Some Error Occured.")
    return render(request,template_name,{'user_id': user_id})
    

def logout_url(request):
    logout(request)
    return redirect('main:index')
    
@login_required
@csrf_exempt
def apply_donate(request,template_name="donate/donate.html"):
    ngos = UserDetials.objects.filter(type=3)
    if request.method == "POST":
        try:
            postdata = request.POST
            food_name = postdata['food_name']
            plate_size = postdata['plate_size']
            reason = postdata['reason']
            ngo_id = postdata['ngo_id']
            try:
                ngo_details_obj = User.objects.get(id=ngo_id)
            except:
                ngo_details_obj = None
            if ngo_details_obj is not None:
                Donations.objects.create(
                    food_name=food_name,
                    plate_size=plate_size,
                    reason = reason,
                    from_user = request.user,
                    to_user = ngo_details_obj,
                    applied_at = datetime.now()
                )
                messages.success(request, "Donation request has sent! Pickup will be at your Door-Step.")
                user_details_obj = UserDetials.objects.get(user__id=request.user.id)
                if user_details_obj.type == '2':
                    return redirect('org:dashboard')
                elif user_details_obj.type == '3':
                    return redirect('ngo:dashboard')
                elif user_details_obj.type == '4':
                    return redirect('user:dashboard')
            else:
                messages.error(request, "Organization not found.")
        except Exception as e:
            print(e)
            messages.error(request, "Some error occured")
    return render(request,template_name,{"ngos_list":ngos})

templates/main/aboutus.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .content {
            width: 1200px;
            height: auto;
            margin: auto;
            color: rgb(0, 0, 0);
            position: relative;
        }

        .content .par {
            padding-left: 20px;
            padding-bottom: 25px;
            font-family: Arial;
            letter-spacing: 1.2px;
            line-height: 30px;
        }

        .content h1 {
            font-family: 'Times New Roman';
            font-size: 50px;
            padding-left: 20px;
            margin-top: 9%;
            letter-spacing: 2px;
        }

        .content .cn {
            width: 160px;
            height: 40px;
            background: green;
            border: none;
            margin-bottom: 10px;
            margin-left: 20px;
            font-size: 18px;
            border-radius: 10px;
            cursor: pointer;
            transition: .4s ease;

        }

        .content .cn a {
            text-decoration: none;
            color: #000;
            transition: .3s ease;
        }

        .cn:hover {
            background-color: #5A6EA5;
        }

        .welcome_img {
            position: absolute;
            top: -80px;
            left: 600px;
            transform: translate(0%, -5%);
            border-radius: 10px;
            padding: 25px;
        }


        /* scrolling window  */
        html {
  scroll-behavior: smooth;
    }

#section2 {
  height: 600px;
}

footer{
    margin-top: 0;
    background-color: #FFC93C;
    text-align: center;
}
.footer-text{
    color: #ffffff;

    padding: 20px 0px;
}
    </style>


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: 0px" href="/"><b>
                    <font size="5" color="#16a085" style="display: inline-block">Save </font>
                    <font size="6" color="#5A6EA5" style="display: inline-block"> Plate </font>
                </b></a> &nbsp &nbsp
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    <li class="nav-item">
                        <a class="nav-link" href="/"><button type="button" class="btn btn-light">Home</button></b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:achivements' %}"><button type="button" class="btn btn-light">Achievments</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/"><b><button type="button"
                            class="btn btn-warning">About</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contributers' %}"><button type="button" class="btn btn-light">Contributers</button></a>
                    </li>


                </ul>



                <a href="{% url 'main:login' %}" class="nav-link active">
                    <button class="btn btn-outline-success" type="submit"><i data-feather="user"></i>
                        Login
                    </button>
                </a>
            </div>
        </div>
    </nav>



    <!-- intro content  -->

 



    <!-- select type og signup  -->


  
    <footer>
        <div class="footer-text">
            2023 © SavePlate
        </div>
    </footer>
{% endblock content %}

templates/main/achievements.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .content {
            width: 1200px;
            height: auto;
            margin: auto;
            color: rgb(0, 0, 0);
            position: relative;
        }

        .content .par {
            padding-left: 20px;
            padding-bottom: 25px;
            font-family: Arial;
            letter-spacing: 1.2px;
            line-height: 30px;
        }

        .content h1 {
            font-family: 'Times New Roman';
            font-size: 50px;
            padding-left: 20px;
            margin-top: 9%;
            letter-spacing: 2px;
        }

        .content .cn {
            width: 160px;
            height: 40px;
            background: green;
            border: none;
            margin-bottom: 10px;
            margin-left: 20px;
            font-size: 18px;
            border-radius: 10px;
            cursor: pointer;
            transition: .4s ease;

        }

        .content .cn a {
            text-decoration: none;
            color: #000;
            transition: .3s ease;
        }

        .cn:hover {
            background-color: #5A6EA5;
        }

        .welcome_img {
            position: absolute;
            top: -80px;
            left: 600px;
            transform: translate(0%, -5%);
            border-radius: 10px;
            padding: 25px;
        }


        /* scrolling window  */
        html {
  scroll-behavior: smooth;
    }

#section2 {
  height: 600px;
}

footer{
    margin-top: 0;
    background-color: #FFC93C;
    text-align: center;
}
.footer-text{
    color: #ffffff;

    padding: 20px 0px;
}
    </style>


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: 0px" href="/"><b>
                    <font size="5" color="#16a085" style="display: inline-block">Save </font>
                    <font size="6" color="#5A6EA5" style="display: inline-block"> Plate </font>
                </b></a> &nbsp &nbsp
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/"><b><button type="button"
                                    class="btn btn-light">Home</button></b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:achivements' %}"><button type="button" class="btn btn-warning">Achievments</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:aboutus' %}"><button type="button" class="btn btn-light">About</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contributers' %}"><button type="button" class="btn btn-light">Contributers</button></a>
                    </li>


                </ul>



                <a href="{% url 'main:login' %}" class="nav-link active">
                    <button class="btn btn-outline-success" type="submit"><i data-feather="user"></i>
                        Login
                    </button>
                </a>
            </div>
        </div>
    </nav>



    <!-- intro content  -->

 



    <!-- select type og signup  -->


  
    <footer>
        <div class="footer-text">
            2023 © SavePlate
        </div>
    </footer>
{% endblock content %}

templates/main/contributers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .content {
            width: 1200px;
            height: auto;
            margin: auto;
            color: rgb(0, 0, 0);
            position: relative;
        }

        .content .par {
            padding-left: 20px;
            padding-bottom: 25px;
            font-family: Arial;
            letter-spacing: 1.2px;
            line-height: 30px;
        }

        .content h1 {
            font-family: 'Times New Roman';
            font-size: 50px;
            padding-left: 20px;
            margin-top: 9%;
            letter-spacing: 2px;
        }

        .content .cn {
            width: 160px;
            height: 40px;
            background: green;
            border: none;
            margin-bottom: 10px;
            margin-left: 20px;
            font-size: 18px;
            border-radius: 10px;
            cursor: pointer;
            transition: .4s ease;

        }

        .content .cn a {
            text-decoration: none;
            color: #000;
            transition: .3s ease;
        }

        .cn:hover {
            background-color: #5A6EA5;
        }

        .welcome_img {
            position: absolute;
            top: -80px;
            left: 600px;
            transform: translate(0%, -5%);
            border-radius: 10px;
            padding: 25px;
        }


        /* scrolling window  */
        html {
  scroll-behavior: smooth;
    }

#section2 {
  height: 600px;
}

footer{
    margin-top: 0;
    background-color: #FFC93C;
    text-align: center;
}
.footer-text{
    color: #ffffff;

    padding: 20px 0px;
}
    </style>


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: 0px" href="/"><b>
                    <font size="5" color="#16a085" style="display: inline-block">Save </font>
                    <font size="6" color="#5A6EA5" style="display: inline-block"> Plate </font>
                </b></a> &nbsp &nbsp
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    <li class="nav-item">
                        <a class="nav-link" href="/"><button type="button" class="btn btn-light">Home</button></b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:achivements' %}"><button type="button" class="btn btn-light">Achievments</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:aboutus' %}"><button type="button" class="btn btn-light">About</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/"><b><button type="button"
                            class="btn btn-warning">Contributers</button></a>
                    </li>


                </ul>



                <a href="{% url 'main:login' %}" class="nav-link active">
                    <button class="btn btn-outline-success" type="submit"><i data-feather="user"></i>
                        Login
                    </button>
                </a>
            </div>
        </div>
    </nav>



    <!-- intro content  -->

 



    <!-- select type og signup  -->


  
    <footer>
        <div class="footer-text">
            2023 © SavePlate
        </div>
    </footer>
{% endblock content %}

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .content {
            width: 1200px;
            height: auto;
            margin: auto;
            color: rgb(0, 0, 0);
            position: relative;
        }

        .content .par {
            padding-left: 20px;
            padding-bottom: 25px;
            font-family: Arial;
            letter-spacing: 1.2px;
            line-height: 30px;
        }

        .content h1 {
            font-family: 'Times New Roman';
            font-size: 50px;
            padding-left: 20px;
            margin-top: 9%;
            letter-spacing: 2px;
        }

        .content .cn {
            width: 160px;
            height: 40px;
            background: green;
            border: none;
            margin-bottom: 10px;
            margin-left: 20px;
            font-size: 18px;
            border-radius: 10px;
            cursor: pointer;
            transition: .4s ease;

        }

        .content .cn a {
            text-decoration: none;
            color: #000;
            transition: .3s ease;
        }

        .cn:hover {
            background-color: #5A6EA5;
        }

        .welcome_img {
            position: absolute;
            top: -80px;
            left: 600px;
            transform: translate(0%, -5%);
            border-radius: 10px;
            padding: 25px;
        }


        /* scrolling window  */
        html {
  scroll-behavior: smooth;
    }

#section2 {
  height: 600px;
}

footer{
    margin-top: 0;
    background-color: #FFC93C;
    text-align: center;
}
.footer-text{
    color: #ffffff;

    padding: 20px 0px;
}
    </style>


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: 0px" href="/"><b>
                    <font size="5" color="#16a085" style="display: inline-block">Save </font>
                    <font size="6" color="#5A6EA5" style="display: inline-block"> Plate </font>
                </b></a> &nbsp &nbsp
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/"><b><button type="button"
                                    class="btn btn-warning">Home</button></b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:achivements' %}"><button type="button" class="btn btn-light">Achievments</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:aboutus' %}"><button type="button" class="btn btn-light">About</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contributers' %}"><button type="button" class="btn btn-light">Contributers</button></a>
                    </li>


                </ul>



                <a href="{% url 'main:login' %}" class="nav-link active">
                    <button class="btn btn-outline-success" type="submit"><i data-feather="user"></i>
                        Login
                    </button>
                </a>
            </div>
        </div>
    </nav>



    <!-- intro content  -->

    <div class="content">
        <h1>No Harm In<br> Conserving Food</h1>
        <p class="par">
            To Reduce Food Waste And To  <br> Redistribute Surplus Food To Those In Need.
        </p>
        <button class="cn"><a class="text-white" href="#section2">Join Us</a></button>
        <div class="welcome_img">
            <img height="400" src="{% static 'img/main/Welcome.webp' %}" alt="">
        </div>
        <br><br><br><br>
    </div>




    <!-- select type og signup  -->


    <div class="registration_type p-5" id="section2">
        <div class="row">
            <div class="col-sm-3">
                <div class="card">
                    <div class="card-body">
                        <center>
                            <h3 class="card-title">User</h3>
                            <br>
                            <img height="150" src="{% static 'img/main/user_icon.png' %}" alt="">
                            <p class="card-text">User is a single contributer, donater like us.
                            </p>
                            <a href="{% url 'main:register' 4 %}" class="btn btn-warning">Register</a>
                        </center>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card">
                    <div class="card-body">
                        <center>
                        <h3 class="card-title text-center">Food Retailer</h3>
                        <br>
                        <img height="150" src="{% static 'img/main/retailer_icon.png' %}" alt="">
                        <p class="card-text">Food reatilers are the one who provide food material in huge qunantity.</p>
                        <a href="{% url 'main:register' 1 %}" class="btn btn-warning">Register</a>
                    </center>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card">
                    <div class="card-body">
                        <center>
                        <h3 class="card-title text-center">NGO</h3>
                        <br>
                        <img height="150" src="{% static 'img/main/ngo_icon.png' %}" alt="">
                        <p class="card-text">Independent of GOV involvement and operate on a not-for-profit basis.</p>
                        <a href="{% url 'main:register' 3 %}" class="btn btn-warning">Register</a>
                    </center>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card">
                    <div class="card-body">
                        <center>
                        <h3 class="card-title text-center">Organisations</h3>
                        <br>
                        <img height="150" src="{% static 'img/main/org_icon.png' %}" alt="">
                        <p class="card-text">Management agencies, Weddings & Parties Organisations</p>
                        <a href="{% url 'main:register' 2 %}" class="btn btn-warning">Register</a>
                    </center>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="footer-text">
            2023 © SavePlate
        </div>
    </footer>
{% endblock content %}

templates/main/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="{% static 'css/main/login.css' %}" rel="stylesheet" />


    <div class="container">
      <div class="flex flex-1">
        <img src="{% static 'img/main/login_icon.jpeg' %}" alt="signupImg" />
      </div>
      <div class="flex flex-2">
        <div class="back-arrow">
          <a href="{% url 'main:index' %}" class="nav-link active">
          <svg
            width="22"
            height="22"
            viewBox="0 0 22 22"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M13.0469 19.9062C13.5156 19.4375 13.4688 18.7344 13.0469 18.2656L7.375 12.875H20.875C21.4844 12.875 22 12.4062 22 11.75V10.25C22 9.64062 21.4844 9.125 20.875 9.125H7.375L13.0469 3.78125C13.4688 3.3125 13.5156 2.60938 13.0469 2.14062L12.0156 1.10938C11.5938 0.6875 10.8438 0.6875 10.4219 1.10938L1.32812 10.25C0.859375 10.6719 0.859375 11.375 1.32812 11.7969L10.4219 20.9375C10.8438 21.3594 11.5469 21.3594 12.0156 20.9375L13.0469 19.9062Z"
              fill="black"
            />
          </svg>
        </a>
        </div>
        <div class="signup-form">
          <div class="signup-title">Login to SavePlate</div>
          <div class="redirect-register">Haven't registered yet? <a href="{% url 'main:index' %}">Register Now</a></div>
<form action="" method="POST">
          <div class="signup-detail">
            <div class="signup-detail-text">Username</div>
            <input type="text" name="username" id="username" class="signup-detail-input" />
            <div class="signup-detail-text">Password</div>
            <input type="password" name="password" id="password" class="signup-detail-input" />
          </div>
          <button type="Submit" class="signup-btn">Login</button>
        </form>
        </div>
      </div>
    </div>
    {% endblock content %}