main/urls.py
from django.urls import path,include
from . import views

app_name = "main"
urlpatterns = [
    path('',views.home,name="index"),
    path('login/',views.login_template,name="login"),
    path('achievements/',views.achievements_template,name="achivements"),
    path('contributers/',views.contributers_template,name="contributers"),
    path('aboutus/',views.aboutus_template,name="aboutus"),
    path('register/<slug:slug>',views.register_template,name="register"),
    path('register2/<slug:user_id>',views.register2_template,name="register2"),
    path('logout',views.logout_url,name="logout"),
    path('apply-to-donate',views.apply_donate,name="apply_donate") 
]

ngo/urls.py
from django.urls import path,include
from . import views

app_name = "ngo"
urlpatterns = [
    path('ngo/dashboard',views.dashboard,name="dashboard"),
]

saveplate/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('',include('user.urls')),
    path('',include('ngo.urls')),
    path('',include('org.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path,include
from . import views

app_name = "user"
urlpatterns = [
    path('user/dashboard',views.dashboard,name="dashboard"),
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from main.models import Donations,UserDetials
from django.contrib import messages 
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User

# Create your views here.
@csrf_exempt
def dashboard(request,template_name="user/dashboard.html"):
    applied_for_donation_list = Donations.objects.filter(from_user__id=request.user.id)
    user_details = UserDetials.objects.get(user__id=request.user.id)
    return render(request,template_name,{'user_details':user_details,'applied_for_donation_list':applied_for_donation_list})

templates/user/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .center_img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}

table {
    position: relative;
    /* left: 50%; */
    top: 50%;
    /* transform: translate(-50%, -50%); */
    border-collapse: collapse;
    width: 1200px;
    /* height: 200px; */
    border: 1px solid #bdc3c7;
    box-shadow: 2px 2px 12px rgba(0, 0, 0, 0.2), -1px -1px 8px rgba(0, 0, 0, 0.2);
    
}

tr {
    transition: all .2s ease-in;
    cursor: pointer;
}

th,
td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

#header {
    background-color: #16a085;
    color: #fff;
}

#title {
    background-color: #888888;
    color: #fff;
}

h1 {
    font-weight: 600;
    text-align: center;
    background-color: #16a085;
    color: #fff;
    padding: 10px 0px;
}

tr:hover {
    background-color: #f5f5f5;
    transform: scale(1.02);
    box-shadow: 2px 2px 12px rgba(0, 0, 0, 0.2), -1px -1px 8px rgba(0, 0, 0, 0.2);
}
#content-table tbody tr:last-of-type{
    border-bottom: 2x solid #009879;
}

@media only screen and (max-width: 768px) {
    table {
        width: 90%;
    }
}
</style>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: 0px" href="/"><b>
                    <font size="5" color="#16a085" style="display: inline-block">Save </font>
                    <font size="6" color="#5A6EA5" style="display: inline-block"> Plate </font>
                </b></a> &nbsp &nbsp
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                </ul>


                &nbsp;
                <button class="btn btn-success" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">Profile</button>
            </div>
        </div>
    </nav>



    <!-- profile side bar -->


    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
        <div class="offcanvas-header">
            <div class="profile_card p-5">
                <center>
                <div class="" style="width: 18rem;">
                    <img class="center_img" height="120" width="50" src="{% static 'img/main/user_icon.png' %}"  alt="">
                    <br>
                    <div class="card-body">
                      <h5 class="card-title">{{request.user.first_name}}</h5>
                      <br>
                      <p class="card-text"><b>Address: </b>{{user_details.address}},{{user_details.city}},{{user_details.state}}-{{user_details.pincode}}</p>
                      <p class="card-text"><b>Phone: {{user_details.phone}} </b></p>
                      <a href="{% url 'main:logout' %}" class="btn btn-warning">Logout</a>
                    </div>
                  </div>
                </center>
            </div>
        </div>
    </div>

<h1 class="text-center">Users</h1>

    <!-- donation card  -->

    <div class="donation_card p-5">
        <div class="text-center">
           
            <div class="body">
                <h3 class="card-title">Charity is an act of <br>Soft Heart</h3><br>
                <p class="card-text">We have delivered food a lots of poor people. Please Support us <br> for every needy people</p><br>
                <a href="{% url 'main:apply_donate' %}" class="btn btn-warning">Donate Now</a>
            </div>
        
        </div>
    </div>

    <div class="col-md-12 mt-1" id="donations" style="display: block;">
        <div class="mb-3 content">
            <div class="card-body">
                <center>
                    <br>
    <table style="border-radius: 20px 20px 0 0; overflow: hidden; ">
        <tbody>
            <tr id="title">
                <th>
                    <h2>&nbsp Donations</h2>
                </th>
    
            </tr>
        </tbody>
    </table>
    
    
    <font size="2">
    
    
        <table id="content-table" class="content-table">
            <thead>
                <tr id="header">
                    <th scope="col">
                        <center>SR. No.</center>
                    </th>
                    <th scope="col">Food Name</th>
                    <th scope="col">NGO Name</th>
                    <th scope="col">No of Plates</th>
                    {% comment %} <th scope="col">Address of NGO</th>            {% endcomment %}
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in applied_for_donation_list%}
                    <th scope='row'><center>{{obj.id}}</center></th>
                    <td>{{obj.food_name}}</td>
                    <td>{{obj.to_user.first_name}}</td>
                    <td>{{obj.plate_size}}</td>
                    {% comment %} <td></td> {% endcomment %}

                    <td>
                    {%if obj.received_status == False%}
                        <button class='btn btn-sm btn-warning'>Not received</button></td>
                    {%elif obj.received_status == True%}
                        <button class='btn btn-sm btn-success'>Received</button></td>
                    {%elif obj.donated_status == True%}
                        <button class='btn btn-sm btn-success'>Donated</button></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </font>
    </div>
    </div></div>





    {% endblock content %}











    